version: '2'
services:
    softtopiaweb-app:
        image: softtopiaweb
        external_links:
            - softtopiaweb-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=softtopiaweb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    softtopiaweb-mongodb:
        extends:
            file: mongodb.yml
            service: softtopiaweb-mongodb
