version: '2'
services:
    softtopiaweb-mongodb:
        container_name: softtopiaweb-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        command: mongos --configdb softtopiaweb-mongodb-config
    softtopiaweb-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    softtopiaweb-mongodb-config:
        image: mongo:3.3.5
        container_name: softtopiaweb-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
